# Etapa 1: Construcción
FROM maven:3.8.8-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# Etapa 2: Ejecución (Mínimo Privilegio)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN addgroup -S devops && adduser -S devopsuser -G devops
COPY --from=build /app/target/*.jar app.jar

USER devopsuser

# Puerto configurado por código en tu properties
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]