# Etapa 1: Construcción con Maven y Java 17
FROM maven:3.8.8-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# Etapa 2: Imagen de ejecución ligera con JRE
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# RÚBRICA: Creación de usuario sin privilegios root
RUN addgroup -S devops && adduser -S devopsuser -G devops
COPY --from=build /app/target/*.jar app.jar

# Cambiamos al usuario sin privilegios antes de correr la app
USER devopsuser

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]