name: Pipeline Express - Actualizar Color Front

on:
  push:
    branches:
      - deploy # ✨ CORREGIDO: Se quitó 'paths' para que corra SÍ O SÍ en cada push

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Conectar al Frontend y Actualizar la Página
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST_FRONTEND }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "==== Destrabando permisos de Git en AWS ===="
          cd /home/ec2-user/Prueba-Devops2
          
          # 1. Evitar el error de 'dubious ownership' si la carpeta es de root
          sudo git config --global --add safe.directory /home/ec2-user/Prueba-Devops2
          
          # 2. Forzar la descarga limpia usando sudo
          sudo git fetch --all
          sudo git reset --hard origin/deploy
          
          echo "==== Reconstruyendo contenedores desde cero absoluto ===="
          # 3. Apagar entorno antiguo
          sudo docker compose down
          
          # 4. Obligar a Docker a compilar el JS de Vite ignorando la caché vieja
          sudo docker compose build --no-cache
          
          # 5. Levantar el Front actualizado
          sudo docker compose up -d --force-recreate
          
          echo "==== ¡Pipeline CI/CD completado sin bloqueos! ===="