name: Pipeline Express - Actualizar Color Front

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**' # Detecta cualquier cambio dentro de tu carpeta del front

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Conectar al Frontend y Actualizar la Página
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST_FRONTEND }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "==== Iniciando actualización forzada del Frontend ===="
          cd /home/ec2-user/Prueba-Devops2
          
          # 1. Bajar el cambio de texto del Navbar desde GitHub
          git pull origin deploy
          
          # 2. Comando infalible: Apaga, limpia la caché, compila el nuevo JS y levanta todo limpio
          sudo docker compose down
          sudo docker compose up -d --build
          
          echo "==== ¡Pipeline CI/CD completado con éxito! ===="